# Generated by Django 4.0.3 on 2022-11-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('roll', models.PositiveIntegerField(max_length=20)),
                ('city', models.CharField(max_length=200)),
            ],
        ),
    ]
