# Generated by Django 4.1.5 on 2023-01-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(error_messages={'required': 'Please enter your name'}, max_length=100),
        ),
    ]
