# Generated by Django 4.0.3 on 2022-12-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='stdclass',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
