# Generated by Django 4.0.3 on 2022-12-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_student_options_alter_student_roll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='stdclass',
            field=models.IntegerField(blank=True),
        ),
    ]
